"""Shell completion scripts for leph and libephemeris CLIs.

Provides `leph completion {zsh,bash,fish}` commands that output custom
completion scripts. Unlike Click's built-in completion, these scripts:

  1. Don't abort when `leph` isn't in PATH (the $+commands guard)
  2. Auto-create a `leph` shell function that delegates to `uv run leph`
  3. Work whether the venv is activated or not
"""

from __future__ import annotations

import click

# ---------------------------------------------------------------------------
# Completion scripts — custom, uv-aware
# ---------------------------------------------------------------------------

_ZSH_SCRIPT = r"""# --- leph shell integration (zsh) ---
# Generated by: leph completion zsh
# Add to ~/.zshrc:  eval "$(uv run leph completion zsh)"
# Or:  uv run leph completion zsh > ~/.leph-completion.zsh
#      echo 'source ~/.leph-completion.zsh' >> ~/.zshrc

# Make 'leph' available without activating the venv.
# If leph is already in PATH (venv activated), this is skipped.
if ! (( $+commands[leph] )) && ! (( $+functions[leph] )); then
    leph() { command uv run leph "$@"; }
fi

_leph_completion() {
    local -a completions completions_with_descriptions response

    # Use the real binary if in PATH, otherwise uv run
    if (( $+commands[leph] )); then
        response=("${(@f)$(env COMP_WORDS="${words[*]}" COMP_CWORD=$((CURRENT-1)) _LEPH_COMPLETE=zsh_complete leph)}")
    else
        response=("${(@f)$(env COMP_WORDS="${words[*]}" COMP_CWORD=$((CURRENT-1)) _LEPH_COMPLETE=zsh_complete uv run leph)}")
    fi

    for type key descr in ${response}; do
        if [[ "$type" == "plain" ]]; then
            if [[ "$descr" == "_" ]]; then
                completions+=("$key")
            else
                completions_with_descriptions+=("$key":"$descr")
            fi
        elif [[ "$type" == "dir" ]]; then
            _path_files -/
        elif [[ "$type" == "file" ]]; then
            _path_files -f
        fi
    done

    if [ -n "$completions_with_descriptions" ]; then
        _describe -V unsorted completions_with_descriptions -U
    fi
    if [ -n "$completions" ]; then
        compadd -U -V unsorted -a completions
    fi
}

compdef _leph_completion leph
"""

_BASH_SCRIPT = r"""# --- leph shell integration (bash) ---
# Generated by: leph completion bash
# Add to ~/.bashrc:  eval "$(uv run leph completion bash)"
# Or:  uv run leph completion bash > ~/.leph-completion.bash
#      echo 'source ~/.leph-completion.bash' >> ~/.bashrc

# Make 'leph' available without activating the venv.
if ! command -v leph &>/dev/null && ! type -t leph &>/dev/null; then
    leph() { command uv run leph "$@"; }
fi

_leph_completion() {
    local IFS=$'\n'
    local response

    if command -v leph &>/dev/null; then
        response=$(env COMP_WORDS="${COMP_WORDS[*]}" COMP_CWORD=$COMP_CWORD \
            _LEPH_COMPLETE=bash_complete leph)
    else
        response=$(env COMP_WORDS="${COMP_WORDS[*]}" COMP_CWORD=$COMP_CWORD \
            _LEPH_COMPLETE=bash_complete uv run leph)
    fi

    COMPREPLY=($response)
    return 0
}

complete -o default -F _leph_completion leph
"""

_FISH_SCRIPT = r"""# --- leph shell integration (fish) ---
# Generated by: leph completion fish
# Add to ~/.config/fish/conf.d/leph.fish:
#   uv run leph completion fish > ~/.config/fish/conf.d/leph.fish

# Make 'leph' available without activating the venv.
if not type -q leph
    function leph
        command uv run leph $argv
    end
end

function _leph_completion
    set -l response
    if type -q leph; and not functions -q leph
        set response (env _LEPH_COMPLETE=fish_complete COMP_WORDS=(commandline -cp) \
            COMP_CWORD=(commandline -t) leph)
    else
        set response (env _LEPH_COMPLETE=fish_complete COMP_WORDS=(commandline -cp) \
            COMP_CWORD=(commandline -t) uv run leph)
    end
    for completion in $response
        echo $completion
    end
end

complete -c leph -f -a "(_leph_completion)"
"""

_SCRIPTS = {
    "zsh": _ZSH_SCRIPT,
    "bash": _BASH_SCRIPT,
    "fish": _FISH_SCRIPT,
}

# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


@click.group(
    "completion",
    short_help="Generate shell completion scripts (zsh, bash, fish).",
    help="Generate shell completion scripts for leph.\n\n"
    "These scripts make TAB completion work and also create a 'leph' shell\n"
    "function so you can type 'leph' directly without activating the venv.\n\n"
    "Quick setup (zsh):\n\n"
    '  eval "$(uv run leph completion zsh)"     # Test it now\n'
    "  uv run leph completion zsh >> ~/.zshrc    # Make it permanent\n\n"
    "After reloading your shell:\n\n"
    "  leph <TAB>               # Shows: test, code, leb, download, ...\n"
    "  leph test <TAB>          # Shows: skyfield, leb-backend, compare, ...\n"
    "  leph test skyfield <TAB> # Shows: essential, smoke, unit, ...",
)
def completion_group() -> None:
    """Shell completion generation."""


@completion_group.command(
    short_help="Print zsh completion script (for ~/.zshrc).",
)
def zsh() -> None:
    """Print zsh completion + shell function script.

    \b
    Quick test:
      eval "$(uv run leph completion zsh)"
    \b
    Permanent setup (pick one):
      # Option A: append to .zshrc
      uv run leph completion zsh >> ~/.zshrc
    \b
      # Option B: separate file
      uv run leph completion zsh > ~/.leph-completion.zsh
      echo 'source ~/.leph-completion.zsh' >> ~/.zshrc
    \b
    Then reload:
      source ~/.zshrc
    """
    click.echo(_SCRIPTS["zsh"])


@completion_group.command(
    short_help="Print bash completion script (for ~/.bashrc).",
)
def bash() -> None:
    """Print bash completion + shell function script.

    \b
    Quick test:
      eval "$(uv run leph completion bash)"
    \b
    Permanent setup:
      uv run leph completion bash >> ~/.bashrc
      source ~/.bashrc
    """
    click.echo(_SCRIPTS["bash"])


@completion_group.command(
    short_help="Print fish completion script (for conf.d/).",
)
def fish() -> None:
    """Print fish completion + shell function script.

    \b
    Setup:
      uv run leph completion fish > ~/.config/fish/conf.d/leph.fish
    """
    click.echo(_SCRIPTS["fish"])
